# Site settings
name: Yassin ElBedwihy
title: Yassin ElBedwihy | Engineering Undergraduate
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://n0rbed.github.io/
baseurl: ''
email: eng.yassin.elbedwihy@gmail.com
cover: https://n0rbed.github.io/img/og.png
logo: https://n0rbed.github.io/img/emojis/technologist.png
resume: https://n0rbed.github.io/resume.pdf
social:
  - title: email
    url: mailto:eng.yassin.elbedwihy@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/yassin.elbedwihy
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/n0rbed
  - title: linkedin
    url: https://www.linkedin.com/in/yassin-elbedwihy-95508a198/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
